# Write Kubernetes Deployment Script

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: part2:1
        ports:
        - containerPort: 7000
        imagePullPolicy: Never
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://sit_722_part2_7acc_user:I30KLSg2MVwyh1s4TIpdfCsdULvrsR2g@dpg-cs2n77jv2p9s73cqdkcg-a.oregon-postgres.render.com/sit_722_part2_7acc"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30000
